// employee actions

export const RESET_EMPLOYEE_DETAILS = 'RESET_EMPLOYEE_DETAILS';
export const GETTING_EMPLOYEE_DETAILS = 'GETTING_EMPLOYEE_DETAILS';
export const GET_EMPLOYEE_DETAILS_SUCCEDED = 'GET_EMPLOYEE_DETAILS_SUCCEDED';